# Generated by Django 6.0.6 on 2026-07-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veeveesh_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='Full_name',
            new_name='full_name',
        ),
    ]
