# Generated by Django 6.0.6 on 2026-07-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veeveesh_portfolio', '0002_rename_full_name_contacts_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
