# Generated by Django 6.0.6 on 2026-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veeveesh_portfolio', '0003_rename_contacts_contact_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='Blog_media', verbose_name=''),
        ),
    ]
