# Generated by Django 6.0.7 on 2026-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veeveesh_portfolio', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=models.TextField(max_length=7000),
        ),
    ]
